In [1]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils


Using TensorFlow backend.


### Load Data

In [45]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [77]:
y_train = np_utils.to_categorical(y_train)

In [79]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [10]:
num_pixels = X_train.shape[1] * X_train.shape[2]

In [73]:
X_test.shape[0]

10000

In [16]:
X_train = X_train.reshape((X_train.shape[0], num_pixels)).astype('float32')
X_test = X_test.reshape((X_test.shape[0], num_pixels)).astype('float32')

In [17]:
X_train.shape

(60000, 784)

In [ ]:
X_train = X_train / 255
X_test = X_test / 255


In [18]:
# Simple CNN for the MNIST Dataset
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils
# load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()
# reshape to be [samples][width][height][channels]
X_train = X_train.reshape((X_train.shape[0], 28, 28, 1)).astype('float32')
X_test = X_test.reshape((X_test.shape[0], 28, 28, 1)).astype('float32')
# normalize inputs from 0-255 to 0-1
X_train = X_train / 255
X_test = X_test / 255
# one hot encode outputs
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
num_classes = y_test.shape[1]
# define a simple CNN model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Conv2D(32, (5, 5), input_shape=(28, 28, 1), activation='relu'))
    model.add(MaxPooling2D())
    model.add(Dropout(0.2))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 39s 643us/step - loss: 0.2423 - accuracy: 0.9303 - val_loss: 0.0720 - val_accuracy: 0.9787
Epoch 2/10
60000/60000 [==============================] - 40s 660us/step - loss: 0.0713 - accuracy: 0.9786 - val_loss: 0.0501 - val_accuracy: 0.9840
Epoch 3/10
60000/60000 [==============================] - 38s 634us/step - loss: 0.0509 - accuracy: 0.9846 - val_loss: 0.0394 - val_accuracy: 0.9875
Epoch 4/10
60000/60000 [==============================] - 39s 647us/step - loss: 0.0404 - accuracy: 0.9873 - val_loss: 0.0384 - val_accuracy: 0.9878
Epoch 5/10
60000/60000 [==============================] - 39s 646us/step - loss: 0.0328 - accuracy: 0.9893 - val_loss: 0.0349 - val_accuracy: 0.9890
Epoch 6/10
60000/60000 [==============================] - 38s 638us/step - loss: 0.02

In [27]:
from keras.callbacks import EarlyStopping  
callback = EarlyStopping(monitor='val_loss', patience=3)
# build the model
model = baseline_model()
# Fit the model
#model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200)
model.fit(X_train, y_train, validation_split=0.1, epochs=20, batch_size=200,callbacks=[callback])
# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("CNN Error: %.2f%%" % (100-scores[1]*100))
print('')

Train on 54000 samples, validate on 6000 samples
Epoch 1/20
54000/54000 [==============================] - 35s 655us/step - loss: 0.2841 - accuracy: 0.9171 - val_loss: 0.0924 - val_accuracy: 0.9750
Epoch 2/20
54000/54000 [==============================] - 36s 668us/step - loss: 0.0909 - accuracy: 0.9721 - val_loss: 0.0588 - val_accuracy: 0.9833
Epoch 3/20
54000/54000 [==============================] - 35s 652us/step - loss: 0.0613 - accuracy: 0.9816 - val_loss: 0.0534 - val_accuracy: 0.9852
Epoch 4/20
54000/54000 [==============================] - 34s 626us/step - loss: 0.0461 - accuracy: 0.9858 - val_loss: 0.0516 - val_accuracy: 0.9867
Epoch 5/20
54000/54000 [==============================] - 34s 626us/step - loss: 0.0374 - accuracy: 0.9886 - val_loss: 0.0471 - val_accuracy: 0.9878
Epoch 6/20
54000/54000 [==============================] - 36s 665us/step - loss: 0.0316 - accuracy: 0.9899 - val_loss: 0.0418 - val_accuracy: 0.9895
Epoch 7/20
54000/54000 [==============================] -

In [33]:
X_train[1]

array([[[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [54]:
noice=0.25*np.random.normal(0, 1.0, size=X_train.shape)

In [80]:
test = X_train+noice


ValueError: operands could not be broadcast together with shapes (60000,28,28) (2,2,2) 

In [81]:
test.shape

(2, 2, 2)

In [82]:
test_1 = np.arange(8).reshape(2, 2, 2)

In [67]:
noice.shape

(2, 2, 2)

In [66]:
noice=0.25*np.random.normal(0, 1.0, size=test_1.shape)

In [69]:
test = test_1+noice

In [72]:
np.clip(test,0,5)


array([[[0.        , 1.20878613],
        [1.86408187, 2.81672793]],

       [[4.21025195, 5.        ],
        [5.        , 5.        ]]])

In [71]:
test

array([[[-0.13634709,  1.20878613],
        [ 1.86408187,  2.81672793]],

       [[ 4.21025195,  5.20741405],
        [ 6.08790973,  6.92017944]]])